# **`Data Science Learners Hub`**

**Module : Python**

**email** : [datasciencelearnershub@gmail.com](mailto:datasciencelearnershub@gmail.com)

#### **`4. Array Attributes:`**

**Exploring NumPy Array Attributes:**

NumPy arrays come with several attributes that provide crucial information about their structure and content. Understanding these attributes is essential for effective array manipulation and analysis. Here are some key attributes:

**Note:**
- `shape`, `ndim` (number of dimensions), `size` and `dtype` are attributes of NumPy arrays, not functions or constants. Attributes are properties associated with an object, and in this context, they provide information about the structure and characteristics of a NumPy array.

Here's a brief explanation of each:

1. **Shape (`shape`):**
   - Represents the dimensions of the array, indicating the size along each axis.
   - Example:
     ```python
     import numpy as np

     arr = np.array([[1, 2, 3], [4, 5, 6]])
     print("Array Shape:", arr.shape)  # Output: (2, 3)
     ```

2. **Size (`size`):**
   - Denotes the total number of elements in the array.
   - Example:
     ```python
     import numpy as np

     arr = np.array([[1, 2, 3], [4, 5, 6]])
     print("Array Size:", arr.size)  # Output: 6
     ```

3. **Dimensions (`ndim`):**
   - Indicates the number of axes or dimensions of the array.
   - Example:
     ```python
     import numpy as np

     arr = np.array([[1, 2, 3], [4, 5, 6]])
     print("Number of Dimensions:", arr.ndim)  # Output: 2
     ```

4. **Data Type (`dtype`):**
   - Specifies the type of elements in the array, such as integers, floats, or others.
   - Example:
     ```python
     import numpy as np

     arr = np.array([1, 2, 3], dtype=float)
     print("Array Data Type:", arr.dtype)  # Output: float64
     ```


**Importance of Understanding Attributes:**

1. **Shape and Broadcasting:**
   - **Scenario:** You have two arrays of different shapes, and you want to perform element-wise operations.
   - **Application:** Understanding the shapes of arrays helps in deciding whether broadcasting (element-wise operations on arrays of different shapes) is possible.

In [1]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array
arr2 = np.array([10, 20, 30]) # Note : here arr2 shape is (3,) its 1D array with 3 columns
result = arr1 + arr2  # Broadcasting works due to matching shapes
print(arr1.shape)
print(arr2.shape)

print(result)

(2, 3)
(3,)
[[11 22 33]
 [14 25 36]]


2. **Memory Usage with Size:**
   - **Scenario:** You are working with large datasets and need to manage memory efficiently.
   - **Application:** Knowing the size of an array allows you to estimate its memory requirements and optimize your program accordingly.

#### Explanation :

**Generating a Random Array:**

- big_array = np.random.random((1000, 1000)): Here, np.random.random((1000, 1000)) generates a NumPy array (specifically a 2D array) of shape 
1000×1000. Each element in this array is a random floating-point number between 0.0 and 1.0.

In [15]:
import numpy as np

big_array = np.random.random((1000, 1000))
print("Memory Usage (MB):", big_array.nbytes / (1024 * 1024))

Memory Usage (MB): 7.62939453125


3. **Dimensionality and Data Analysis:**
   - **Scenario:** You are analyzing a dataset with multiple variables.
   - **Application:** The number of dimensions (`ndim`) indicates the number of variables, aiding in data exploration and analysis.

In [2]:
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Number of Variables:", data.ndim)  # Output: 2
print(data.shape)

Number of Variables: 2
(3, 3)


4. **Data Type and Precision:**
   - **Scenario:** You are working with financial data and need precise calculations.
   - **Application:** Specifying the data type helps control the precision of calculations, which is crucial in financial and scientific applications.

In [17]:
import numpy as np

financial_data = np.array([100.25, 150.67, 200.32], dtype=np.float32)
print(financial_data)

[100.25 150.67 200.32]


Understanding these attributes enhances your ability to manipulate and analyze data efficiently, leading to more effective use of NumPy in practical scenarios.