# **`Data Science Learners Hub`**

**Module : Python**

**email** : [datasciencelearnershub@gmail.com](mailto:datasciencelearnershub@gmail.com)

### **`#2: Operations on NumPy Arrays`**

1. **Element-wise Operations:**
   - Performing basic arithmetic operations on arrays.
   - Universal functions (ufuncs) in NumPy.

2. **Aggregation and Statistics:**
   - Sum, mean, median, variance, and standard deviation.
   - Min, max, and other aggregation functions.

3. **Array Comparison and Boolean Operations:**
   - Comparing arrays element-wise.
   - Boolean indexing and masking.

4. **Array Manipulation:**
   - Reshaping arrays.
   - Concatenation and splitting arrays.

### **`2.3. Array Comparison and Boolean Operations in NumPy:`**

**Importance:**

Array comparison and boolean operations in NumPy are fundamental for creating conditions, filtering data, and making logical decisions. These operations involve comparing elements in arrays and generating boolean arrays as a result.

**Scenarios:**

1. **Filtering Data:**
   - **Scenario:** Identifying temperatures above a certain threshold in weather data.
   - **Application:** Use boolean operations to filter temperatures exceeding a specified threshold for further analysis.

In [6]:
import numpy as np

temperatures = np.array([22, 25, 30, 35, 28, 24, 32])
above_threshold = temperatures > 25
filtered_temperatures = temperatures[above_threshold]
print(filtered_temperatures)

[30 35 28 32]


2. **Scientific Experiments:**
   - **Scenario:** Analyzing experimental results based on specific criteria.
   - **Application:** Use boolean operations to filter and analyze experimental data meeting specific conditions.

In [7]:
import numpy as np

experiment_results = np.array([12, 18, 22, 15, 30, 25, 20])
successful_experiments = experiment_results >= 20
analysis_data = experiment_results[successful_experiments]
print(analysis_data)

[22 30 25 20]


3. **Financial Analysis:**
   - **Scenario:** Identifying profitable stock trades based on certain indicators.
   - **Application:** Use boolean operations to filter stock trades with favorable conditions.

In [8]:
import numpy as np

stock_prices = np.array([150, 160, 140, 170, 180, 130])
profitable_trades = stock_prices > 150
selected_trades = stock_prices[profitable_trades]
print(selected_trades)

[160 170 180]


**Real-world Examples:**

1. **Medical Research:**
   - **Scenario:** Analyzing patient data for specific conditions.
   - **Application:** Identify patients with a certain health parameter above a threshold using boolean operations for targeted medical analysis.

2. **Environmental Monitoring:**
   - **Scenario:** Identifying pollution levels above safety standards.
   - **Application:** Use boolean operations to filter data from environmental sensors, focusing on instances when pollution levels exceed acceptable standards.

3. **Educational Assessment:**
   - **Scenario:** Identifying students who scored above a passing grade.
   - **Application:** Use boolean operations to filter and analyze student scores, focusing on those who met or exceeded passing criteria.

**Key Takeaway:**

Array comparison and boolean operations in NumPy provide a powerful mechanism for filtering and analyzing data based on specific conditions. These operations are crucial in various real-world applications, including weather analysis, scientific experiments, financial decision-making, medical research, environmental monitoring, and educational assessments. They enable users to focus on relevant data subsets, make informed decisions, and extract meaningful insights from datasets.