# **`Data Science Learners Hub`**

**Module : Python**

**email** : [datasciencelearnershub@gmail.com](mailto:datasciencelearnershub@gmail.com)

### **`#3: Advanced Topics in NumPy`**

1. **Broadcasting:**
   - Understanding how NumPy handles operations on arrays of different shapes.
   - Examples illustrating broadcasting.

2. **Linear Algebra with NumPy:**
   - Matrix multiplication.
   - Solving linear equations using NumPy.

3. **Random in NumPy:**
   - Generating random numbers with `np.random`.
   - Simulating random processes.

4. **File I/O with NumPy:**
   - Reading and writing data to files using `np.loadtxt` and `np.savetxt`.
   - Saving and loading NumPy arrays using `np.save` and `np.load`.




#### **`1. Broadcasting in NumPy:`**

**Concept:**

Broadcasting is a powerful feature in NumPy that allows for element-wise operations between arrays of different shapes and sizes. In simpler terms, it enables NumPy to perform operations on arrays that don't have the same shape by implicitly replicating and aligning smaller arrays to match the shape of larger arrays.

**How Broadcasting Works:**

When operating on two arrays, NumPy compares their shapes element-wise, starting from the rightmost dimensions. It automatically adds dimensions to the smaller array to make their shapes compatible. Broadcasting continues until the shapes are aligned, allowing element-wise operations.

**Example:**


In [2]:
import numpy as np

# Broadcasting Example
arr1 = np.array([1, 2, 3])
arr2 = np.array([[10], [20], [30]])

print('arr1.shape :', arr1.shape)
print('arr2.shape :', arr2.shape)

result = arr1 + arr2
print(result)
print('result.shape :',result.shape)

arr1.shape : (3,)
arr2.shape : (3, 1)
[[11 12 13]
 [21 22 23]
 [31 32 33]]
result.shape : (3, 3)


In this example, `arr1` has shape (3,) and `arr2` has shape (3, 1). NumPy automatically broadcasts `arr1` to shape (1, 3) so that the addition operation can be performed element-wise. The resulting `result` has shape (3, 3).

**Real-world Examples:**

1. **Temperature Conversion:**
   - **Scenario:** Convert temperatures in Celsius to Fahrenheit.
   - **Application:** Broadcasting allows converting an array of Celsius temperatures to Fahrenheit without the need for explicit looping.

In [3]:
import numpy as np

celsius_temps = np.array([0, 10, 20, 30, 40])
# Broadcasting to convert Celsius to Fahrenheit: (C * 9/5) + 32
fahrenheit_temps = (celsius_temps * 9/5) + 32

print(fahrenheit_temps)

[ 32.  50.  68.  86. 104.]


2. **Stock Portfolio Analysis:**
   - **Scenario:** Calculate the total value of a stock portfolio.
   - **Application:** Broadcasting enables multiplying the number of shares by the stock prices for each stock, even if the shapes are different.

In [4]:
import numpy as np

shares_owned = np.array([10, 20, 30])
stock_prices = np.array([50, 75, 100])
# Broadcasting to calculate total value: shares_owned * stock_prices
portfolio_value = shares_owned * stock_prices

print(portfolio_value)

[ 500 1500 3000]


3. **Image Brightness Adjustment:**
   - **Scenario:** Adjust the brightness of an image.
   - **Application:** Broadcasting facilitates scaling the pixel values of an image without the need for explicit loops.

In [5]:
import numpy as np

image = np.array([[100, 150], [200, 250]])
# Broadcasting to increase brightness by 50: image + 50
brighter_image = image + 50
print(brighter_image)

[[150 200]
 [250 300]]


**Key Takeaway:**

Broadcasting in NumPy is a powerful mechanism that simplifies operations on arrays with different shapes, making code more concise and readable. It is particularly useful in scenarios involving numerical operations, data manipulation, and transformations, contributing to the efficiency and flexibility of array-based computations in various applications.

#### **`4. Linear Algebra with NumPy:`**

**1. Matrix Multiplication:**

- **Scenario:** Financial Portfolio Optimization
- **Application:** Matrix multiplication is crucial in finance for optimizing a portfolio. If `A` represents the returns of different assets and `B` represents the weights of these assets in the portfolio, then the product `C = A * B` gives the expected portfolio returns.

In [6]:
import numpy as np

returns = np.array([[0.05, 0.03], [0.02, 0.04]])  # Asset returns matrix
weights = np.array([[0.4], [0.6]])  # Portfolio weights matrix

# Portfolio returns: C = A * B
portfolio_returns = np.dot(returns, weights)

print(portfolio_returns)

[[0.038]
 [0.032]]


**2. Solving Linear Equations:**

- **Scenario:** Engineering Stress Analysis
- **Application:** Linear algebra is used in engineering to solve systems of linear equations. If `A` represents the material properties, `B` represents the applied forces, and `X` represents the resulting strains, then the equation `AX = B` can be solved using NumPy.

In [7]:
import numpy as np

material_properties = np.array([[2, -1], [1, 3]])  # Material properties matrix
applied_forces = np.array([[10], [5]])  # Applied forces matrix

# Solve linear equations: AX = B
strains = np.linalg.solve(material_properties, applied_forces)

print(strains)

[[5.]
 [0.]]


**Real-world Examples:**

1. **Structural Engineering: Finite Element Analysis**
   - **Scenario:** Analyzing stresses and strains in structural elements.
   - **Application:** Linear algebra operations are employed to solve complex systems of linear equations arising in finite element analysis for structural engineering.

In [10]:
import numpy as np

stiffness_matrix = np.array([[1000, -500], [-500, 800]])  # Stiffness matrix
applied_forces = np.array([[100], [50]])  # Applied forces matrix

# Solve linear equations: AX = B
displacements = np.linalg.solve(stiffness_matrix, applied_forces)

print(displacements)

[[0.19090909]
 [0.18181818]]


2. **Machine Learning: Linear Regression**
   - **Scenario:** Predicting house prices based on features.
   - **Application:** Linear algebra is used in linear regression models. If `X` represents feature values, `Y` represents target values, and `W` represents weights, then the equation `Y = XW` involves matrix multiplication.

In [11]:
import numpy as np

features = np.array([[1, 2000], [1, 2500], [1, 1800]])  # Features matrix
weights = np.array([[500], [0.2]])  # Weights matrix

# Predict house prices: Y = XW
predicted_prices = np.dot(features, weights)

print(predicted_prices)

[[ 900.]
 [1000.]
 [ 860.]]


**Key Takeaway:**

NumPy's linear algebra capabilities make it a powerful tool for solving problems in various fields. Whether it's optimizing financial portfolios, analyzing stress in engineering structures, performing image transformations, or implementing machine learning algorithms, linear algebra with NumPy provides a versatile and efficient framework for numerical computations.

#### **`3. Random Number Generation in NumPy:`**

**Using the `np.random` Module:**

NumPy provides a comprehensive set of functions for random number generation through the `np.random` module. Some key functions include:

1. **`np.random.rand`:** Generates random numbers from a uniform distribution over `[0, 1)`.

In [12]:
import numpy as np

random_numbers = np.random.rand(3, 2)  # Generate a 3x2 array of random numbers

print(random_numbers)

[[0.91929137 0.80345834]
 [0.7376449  0.71288324]
 [0.0975569  0.87228412]]


2. **`np.random.randn`:** Generates random numbers from a standard normal distribution (mean=0, std=1).

In [2]:
import numpy as np

random_numbers = np.random.randn(5)  # Generate an array of 5 random numbers from a standard normal distribution

print(random_numbers)

[ 0.90189377 -1.6388481  -0.05805631  0.67198547  1.09089933]


3. **`np.random.randint`:** Generates random integers from a specified low (inclusive) to high (exclusive) range.

In [14]:
import numpy as np

random_integers = np.random.randint(1, 10, size=(2, 3))  # Generate a 2x3 array of random integers between 1 and 10

print(random_integers)

[[3 2 6]
 [9 9 9]]


4. **`np.random.choice`:** Generates random samples from a given 1-D array or sequence.

In [15]:
import numpy as np

choices = np.random.choice(['red', 'blue', 'green'], size=5)  # Randomly choose 5 colors from the given array

print(choices)

['red' 'red' 'green' 'red' 'red']


**Real-world Examples:**

1. **Monte Carlo Simulations:**
   - **Scenario:** Financial risk assessment.
   - **Application:** In finance, random number generation is crucial for Monte Carlo simulations. Simulating various market scenarios helps assess the risk associated with different investment strategies.

In [16]:
   import numpy as np

   num_simulations = 1000
   returns = np.random.randn(num_simulations, 10)  # Simulate returns for 10 financial assets in 1000 scenarios

   print(returns)

[[-2.97490528e-01 -1.44284272e+00  1.94835145e+00 ... -2.35400858e+00
   7.62862264e-01 -3.15095891e-01]
 [-1.89689009e+00  1.40780633e+00 -2.90971529e-01 ... -1.17548345e+00
   8.69624484e-01 -1.15555771e-01]
 [ 1.73351735e+00 -2.44816245e-01  3.52849723e-01 ...  6.85412289e-01
   7.55002148e-01  2.19141519e-01]
 ...
 [-8.24837955e-01  1.01163372e+00  1.50986813e-01 ... -5.36100325e-01
   1.49036366e+00 -1.20282482e-01]
 [ 1.25412824e+00  6.95825732e-01  4.10119612e-01 ... -5.64046256e-01
  -5.67529745e-01 -8.71055961e-01]
 [-4.40572458e-01 -9.57697080e-03  1.59207655e+00 ...  1.00257586e+00
   1.70432589e-04  6.89891842e-01]]


2. **Game Development:**
   - **Scenario:** Randomizing elements in a game.
   - **Application:** In game development, random numbers are used to introduce variability. For example, generating random starting positions, enemy behavior, or loot drops.

In [17]:
import numpy as np

enemy_positions = np.random.rand(10, 2) * 100  # Randomize starting positions for 10 enemies within a 100x100 game area

print(enemy_positions)

[[52.01175702  8.50969695]
 [ 4.01636369 98.31398012]
 [95.15361123 19.59324578]
 [98.0224175  89.71041527]
 [94.97842292 24.94124281]
 [79.49416651 84.74824063]
 [85.41762146 57.30224287]
 [83.68133912 21.95428976]
 [32.34198656 15.04745931]
 [ 4.37190816 84.21603481]]


3. **Scientific Experiments:**
   - **Scenario:** Simulating experimental conditions.
   - **Application:** In scientific research, random number generation is used to simulate conditions for experiments. For example, randomly assigning participants to control and experimental groups.

In [18]:
import numpy as np

experimental_group = np.random.choice([0, 1], size=50)  # Simulate random assignment of participants to experimental group (1) or control group (0)

print(experimental_group)

[0 1 1 1 0 1 0 1 0 1 1 0 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 1 1 0 1 1 0 0
 1 1 1 1 1 1 1 1 1 0 1 1 0]


**Key Takeaway:**

NumPy's `np.random` module is a versatile tool for generating random numbers, and its applications extend across various domains. Whether it's for financial simulations, game development, scientific experiments, or machine learning, the ability to generate random numbers is essential for introducing variability and uncertainty into simulations and algorithms.

#### **`4. File I/O with NumPy:`**

NumPy provides convenient functions for reading and writing data to files, making it easy to handle data persistence in various formats. Here are key functions for file I/O in NumPy:

1. **`np.savetxt`:** Saves an array to a text file.

In [20]:
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6]])
np.savetxt('output.txt', data, delimiter=',')

# Note : 'output.txt' file gets created in ur current working directory

2. **`np.loadtxt`:** Loads data from a text file.

In [23]:
import numpy as np

loaded_data = np.loadtxt('input.txt', delimiter=',')

print(loaded_data)

[12. 12. 13.  2.]


3. **`np.save`:** Saves a single array to a binary file with a `.npy` extension.

In [24]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])
np.save('output.npy', data)

# Note : 'output.npy' file gets created in ur current working directory

4. **`np.load`:** Loads a `.npy` file.

In [25]:
import numpy as np

loaded_data = np.load('input.npy')

print(loaded_data)

[1 2 3 4 5]


**Real-world Examples:**

1. **Scientific Data Logging:**
   - **Scenario:** Recording experimental data.
   - **Application:** In scientific experiments, data collected from sensors or instruments can be saved to a file using `np.savetxt` for later analysis or sharing.

   ```python
   import numpy as np

   experiment_data = np.array([[time1, sensor1_value], [time2, sensor2_value], ...])
   np.savetxt('experiment_results.txt', experiment_data, delimiter=',', header='Time, Sensor Value', comments='')
   ```

2. **Financial Data Storage:**
   - **Scenario:** Saving stock price data.
   - **Application:** In finance, historical stock prices can be stored in a file using `np.savetxt` for building and backtesting trading strategies.

   ```python
   import numpy as np

   stock_prices = np.array([[date1, price1], [date2, price2], ...])
   np.savetxt('stock_prices.csv', stock_prices, delimiter=',', header='Date, Closing Price', comments='')
   ```


3. **Simulation Results Storage:**
   - **Scenario:** Storing simulation outcomes.
   - **Application:** In simulations, results can be saved to a file using `np.savetxt` for subsequent analysis or comparison.

   ```python
   import numpy as np

   simulation_results = np.array([[iteration1, outcome1], [iteration2, outcome2], ...])
   np.savetxt('simulation_results.txt', simulation_results, delimiter=',', header='Iteration, Outcome', comments='')
   ```


**Key Takeaway:**

NumPy's file I/O functions are valuable for handling data in various formats, whether for scientific experiments, financial analysis, machine learning, or simulations. These functions provide a seamless way to save and load numerical data, promoting data persistence and facilitating collaboration and reproducibility in data-driven workflows.