# **`Data Science Learners Hub`**

**Module : Python**

**email** : [datasciencelearnershub@gmail.com](mailto:datasciencelearnershub@gmail.com)

### **`#3: Advanced Topics in NumPy`**

1. **Broadcasting:**
   - Understanding how NumPy handles operations on arrays of different shapes.
   - Examples illustrating broadcasting.

2. **Linear Algebra with NumPy:**
   - Matrix multiplication.
   - Solving linear equations using NumPy.

3. **Random in NumPy:**
   - Generating random numbers with `np.random`.
   - Simulating random processes.

4. **File I/O with NumPy:**
   - Reading and writing data to files using `np.loadtxt` and `np.savetxt`.
   - Saving and loading NumPy arrays using `np.save` and `np.load`.




### **`3.2. Linear Algebra with NumPy:`**

**1. Matrix Multiplication:**

- **Scenario:** Financial Portfolio Optimization
- **Application:** Matrix multiplication is crucial in finance for optimizing a portfolio. If `A` represents the returns of different assets and `B` represents the weights of these assets in the portfolio, then the product `C = A * B` gives the expected portfolio returns.

In [6]:
import numpy as np

returns = np.array([[0.05, 0.03], [0.02, 0.04]])  # Asset returns matrix
weights = np.array([[0.4], [0.6]])  # Portfolio weights matrix

# Portfolio returns: C = A * B
portfolio_returns = np.dot(returns, weights)

print(portfolio_returns)

[[0.038]
 [0.032]]


**2. Solving Linear Equations:**

- **Scenario:** Engineering Stress Analysis
- **Application:** Linear algebra is used in engineering to solve systems of linear equations. If `A` represents the material properties, `B` represents the applied forces, and `X` represents the resulting strains, then the equation `AX = B` can be solved using NumPy.

In [7]:
import numpy as np

material_properties = np.array([[2, -1], [1, 3]])  # Material properties matrix
applied_forces = np.array([[10], [5]])  # Applied forces matrix

# Solve linear equations: AX = B
strains = np.linalg.solve(material_properties, applied_forces)

print(strains)

[[5.]
 [0.]]


**Real-world Examples:**

1. **Structural Engineering: Finite Element Analysis**
   - **Scenario:** Analyzing stresses and strains in structural elements.
   - **Application:** Linear algebra operations are employed to solve complex systems of linear equations arising in finite element analysis for structural engineering.

In [10]:
import numpy as np

stiffness_matrix = np.array([[1000, -500], [-500, 800]])  # Stiffness matrix
applied_forces = np.array([[100], [50]])  # Applied forces matrix

# Solve linear equations: AX = B
displacements = np.linalg.solve(stiffness_matrix, applied_forces)

print(displacements)

[[0.19090909]
 [0.18181818]]


2. **Machine Learning: Linear Regression**
   - **Scenario:** Predicting house prices based on features.
   - **Application:** Linear algebra is used in linear regression models. If `X` represents feature values, `Y` represents target values, and `W` represents weights, then the equation `Y = XW` involves matrix multiplication.

In [11]:
import numpy as np

features = np.array([[1, 2000], [1, 2500], [1, 1800]])  # Features matrix
weights = np.array([[500], [0.2]])  # Weights matrix

# Predict house prices: Y = XW
predicted_prices = np.dot(features, weights)

print(predicted_prices)

[[ 900.]
 [1000.]
 [ 860.]]


**Key Takeaway:**

NumPy's linear algebra capabilities make it a powerful tool for solving problems in various fields. Whether it's optimizing financial portfolios, analyzing stress in engineering structures, performing image transformations, or implementing machine learning algorithms, linear algebra with NumPy provides a versatile and efficient framework for numerical computations.

#### **`Understanding Matrices`**

**Matrix Addition** : https://www.youtube.com/watch?v=ZCmVpGv6_1g

**Matrix Multiplication**: 

https://www.youtube.com/watch?v=o6tGHLkZvVM

https://youtu.be/RE-nDY2aWso

Multiplication in Numpy is of two types
- Element wise mul
- dot product mul


In [2]:
# What is the output of this ?

import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("-----Matrix A------")
print(A)
print("-----Matrix B------")
print(B)
print("-----A*B------") #Element wise multiplication
print(a*b)

C = np.matmul(A,B)
print("-----Matrix Mul------")
print(C)

D = np.dot(A,B)
print("-----Dot Mul------")
print(D)

# Note : the output of a*b, c and d


-----Matrix A------
[[1 2]
 [3 4]]
-----Matrix B------
[[5 6]
 [7 8]]
-----A*B------
[[ 5 12]
 [21 32]]
-----Matrix Mul------
[[19 22]
 [43 50]]
-----Dot Mul------
[[19 22]
 [43 50]]


#### Explanation:

- **`matmul()` vs. `dot()` Difference:**
  - In the context of 2D arrays (matrices), both `matmul()` and `dot()` functions perform matrix multiplication (dot product).
  - The key difference is how they handle 2D arrays versus higher-dimensional arrays:
    - `matmul()` is specifically designed for matrix multiplication. It treats both 1-D and 2-D arrays as matrices and performs matrix multiplication accordingly.
    - `dot()` has more flexibility. It handles matrix multiplication for 2-D arrays but behaves differently for higher-dimensional arrays.

In most cases involving 2D arrays, `matmul()` and `dot()` will produce the same result. However, for clarity and readability, it is recommended to use `matmul()` when explicitly performing matrix multiplication to convey the intent of the operation.

#### Note:

- Matrices A(mxn), B(nxp) then 'n' should be matching in case of Dot products. The resultant matrix will have order of mxn
- Dot product of A.B is not equal to B.A i.e they dont have associative product.