# **`Data Science Learners Hub`**

**Module : Python**

**email** : [datasciencelearnershub@gmail.com](mailto:datasciencelearnershub@gmail.com)

### **`#3: Advanced Topics in NumPy`**

1. **Broadcasting:**
   - Understanding how NumPy handles operations on arrays of different shapes.
   - Examples illustrating broadcasting.

2. **Linear Algebra with NumPy:**
   - Matrix multiplication.
   - Solving linear equations using NumPy.

3. **Random in NumPy:**
   - Generating random numbers with `np.random`.
   - Simulating random processes.

4. **File I/O with NumPy:**
   - Reading and writing data to files using `np.loadtxt` and `np.savetxt`.
   - Saving and loading NumPy arrays using `np.save` and `np.load`.




#### **`1. Broadcasting in NumPy:`**

**Concept:**

Broadcasting is a powerful feature in NumPy that allows for element-wise operations between arrays of different shapes and sizes. In simpler terms, it enables NumPy to perform operations on arrays that don't have the same shape by implicitly replicating and aligning smaller arrays to match the shape of larger arrays.

**How Broadcasting Works:**

When operating on two arrays, NumPy compares their shapes element-wise, starting from the rightmost dimensions. It automatically adds dimensions to the smaller array to make their shapes compatible. Broadcasting continues until the shapes are aligned, allowing element-wise operations.

**Example:**


In [2]:
import numpy as np

# Broadcasting Example
arr1 = np.array([1, 2, 3])
arr2 = np.array([[10], [20], [30]])

print('arr1.shape :', arr1.shape)
print('arr2.shape :', arr2.shape)

result = arr1 + arr2
print(result)
print('result.shape :',result.shape)

arr1.shape : (3,)
arr2.shape : (3, 1)
[[11 12 13]
 [21 22 23]
 [31 32 33]]
result.shape : (3, 3)


In this example, `arr1` has shape (3,) and `arr2` has shape (3, 1). NumPy automatically broadcasts `arr1` to shape (1, 3) so that the addition operation can be performed element-wise. The resulting `result` has shape (3, 3).

#### **`Understanding Broadcasting`**

**YouTube Videos** :

[https://youtu.be/0u9OzBSRZec](https://youtu.be/0u9OzBSRZec)

[https://youtu.be/oG1t3qlzq14](https://youtu.be/oG1t3qlzq14)

#### **`Broadcasting Rules in NumPy`:**

NumPy's broadcasting rules determine how arrays with different shapes are combined in element-wise operations. Broadcasting allows NumPy to perform operations on arrays of different shapes without the need for explicit looping. The key broadcasting rules are as follows:

1. **Dimensions Compatibility:**
   - Two dimensions are compatible when they are equal or one of them is 1.
   - For example, a 3x5 array can be broadcasted with a 1x5 array, as their dimensions are compatible.

2. **Size Compatibility:**
   - Arrays with smaller dimensions are padded with ones on their left side until their shapes match.
   - For example, a 3x1 array can be broadcasted with a 3x5 array by duplicating its column along the new axis.

3. **Arrays with the Same Number of Dimensions:**
   - If two arrays have the same number of dimensions, their shapes must be compatible along each dimension.
   - For example, a 3x5 array can be broadcasted with another 3x5 array.

4. **Broadcasting Along Multiple Dimensions:**
   - Broadcasting extends to multiple dimensions simultaneously, but it must follow the rules for each dimension.
   - For example, a 3x1x5 array can be broadcasted with a 1x4x1 array.

5. **Size of 1 Dimensions:**
   - Any dimension with size 1 is considered to be effectively stretched or repeated.
   - For example, a 3x1 array can be broadcasted with a 1x5 array.

6. **No Broadcasting:**
   - If the sizes along a particular dimension do not match and none of them is 1, NumPy raises a "ValueError" indicating an incompatible shape for broadcasting.

### Examples:



In [8]:

import numpy as np

# Example 1: Broadcasting with a scalar
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
scalar_value = 10
result = arr1 + scalar_value
print(f"Shape of arr1 : {arr1.shape}")
print(f'arr1 dimension : {arr1.ndim}')
print(result)


Shape of arr1 : (2, 3)
arr1 dimension : 2
[[11 12 13]
 [14 15 16]]


In [6]:
# Example 2: Broadcasting with a 1D array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

result = arr1 + arr2

print(f"Shape of arr1 : {arr1.shape}")
print(f'arr1 dimension : {arr1.ndim}')
print(f"Shape of arr2 : {arr2.shape}")
print(f'arr2 dimension : {arr2.ndim}')

print(result)

Shape of arr1 : (2, 3)
arr1 dimension : 2
Shape of arr2 : (3,)
arr2 dimension : 1
[[11 22 33]
 [14 25 36]]


In [7]:
# Example 3: Broadcasting with a 2D array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[10], [20]])
result = arr1 + arr2

print(f"Shape of arr1 : {arr1.shape}")
print(f'arr1 dimension : {arr1.ndim}')
print(f"Shape of arr2 : {arr2.shape}")
print(f'arr2 dimension : {arr2.ndim}')

print(result)

Shape of arr1 : (2, 3)
arr1 dimension : 2
Shape of arr2 : (2, 1)
arr2 dimension : 2
[[11 12 13]
 [24 25 26]]


These examples showcase how NumPy follows the broadcasting rules to perform element-wise operations efficiently across arrays with different shapes. Broadcasting is a powerful feature that simplifies operations and enhances the flexibility of array manipulation in NumPy.


#### Example 1: Broadcasting with a Scalar

```
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
scalar_value = 10
result = arr1 + scalar_value
print("Original Array:")
print(arr1)
print("\nBroadcasting with Scalar:")
print(result)

```

**Output:**

```
Original Array:
[[1 2 3]
 [4 5 6]]

Broadcasting with Scalar:
[[11 12 13]
 [14 15 16]]

```

In this example, the scalar value (10) is broadcasted to each element of the array `arr1`.

**Explanation:**

- **Broadcasting Operation:** The scalar value (10) is broadcasted to each element of the array `arr1`.
- **Broadcasting Rule:** Broadcasting with a scalar involves extending the scalar to match the shape of the array.
- **Result:** Each element of `arr1` is added to the scalar value, resulting in the broadcasted array `result`.

#### Example 2: Broadcasting with a 1D Array

```
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2
print("Original Arrays:")
print(arr1)
print(arr2)
print("\nBroadcasting with 1D Array:")
print(result)

```

**Output:**

```
Original Arrays:
[[1 2 3]
 [4 5 6]]
[10 20 30]

Broadcasting with 1D Array:
[[11 22 33]
 [14 25 36]]

```

In this example, the 1D array `arr2` is broadcasted along its axis to match the shape of `arr1`, and element-wise addition is performed.

**Explanation:**

- **Broadcasting Operation:** The 1D array `arr2` is broadcasted along its axis to match the shape of `arr1`.
- **Broadcasting Rule:** Broadcasting with a 1D array involves extending the smaller dimension (here, the row) to match the larger dimension (row-wise broadcasting).
- **Result:** Element-wise addition is performed between `arr1` and the broadcasted `arr2`, resulting in the broadcasted array `result`.

#### Example 3: Broadcasting with a 2D Array

```
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[10], [20]])
result = arr1 + arr2
print("Original Arrays:")
print(arr1)
print(arr2)
print("\nBroadcasting with 2D Array:")
print(result)

```

**Output:**

```
Original Arrays:
[[1 2 3]
 [4 5 6]]
[[10]
 [20]]

Broadcasting with 2D Array:
[[11 12 13]
 [24 25 26]]

```

In this example, the 2D array `arr2` is broadcasted along its axis to match the shape of `arr1`, and element-wise addition is performed.

**Explanation:**

- **Broadcasting Operation:** The 2D array `arr2` is broadcasted along its axis to match the shape of `arr1`.
- **Broadcasting Rule:** Broadcasting with a 2D array involves extending both dimensions to match the larger shape (both row-wise and column-wise broadcasting).
- **Result:** Element-wise addition is performed between `arr1` and the broadcasted `arr2`, resulting in the broadcasted array `result`.

In summary, broadcasting involves extending smaller dimensions to match larger dimensions, enabling element-wise operations between arrays with different shapes. It allows NumPy to perform operations efficiently and without the need for explicit looping or copying of data. The broadcasting rules ensure that the shapes align correctly for element-wise operations.

These examples demonstrate how broadcasting works in different scenarios, allowing NumPy to handle operations between arrays with different shapes in a convenient and efficient manner.

**Real-world Examples:**

1. **Temperature Conversion:**
   - **Scenario:** Convert temperatures in Celsius to Fahrenheit.
   - **Application:** Broadcasting allows converting an array of Celsius temperatures to Fahrenheit without the need for explicit looping.

In [3]:
import numpy as np

celsius_temps = np.array([0, 10, 20, 30, 40])
# Broadcasting to convert Celsius to Fahrenheit: (C * 9/5) + 32
fahrenheit_temps = (celsius_temps * 9/5) + 32

print(fahrenheit_temps)

[ 32.  50.  68.  86. 104.]


2. **Stock Portfolio Analysis:**
   - **Scenario:** Calculate the total value of a stock portfolio.
   - **Application:** Broadcasting enables multiplying the number of shares by the stock prices for each stock, even if the shapes are different.

In [4]:
import numpy as np

shares_owned = np.array([10, 20, 30])
stock_prices = np.array([50, 75, 100])
# Broadcasting to calculate total value: shares_owned * stock_prices
portfolio_value = shares_owned * stock_prices

print(portfolio_value)

[ 500 1500 3000]


3. **Image Brightness Adjustment:**
   - **Scenario:** Adjust the brightness of an image.
   - **Application:** Broadcasting facilitates scaling the pixel values of an image without the need for explicit loops.

In [5]:
import numpy as np

image = np.array([[100, 150], [200, 250]])
# Broadcasting to increase brightness by 50: image + 50
brighter_image = image + 50
print(brighter_image)

[[150 200]
 [250 300]]


**Key Takeaway:**

Broadcasting in NumPy is a powerful mechanism that simplifies operations on arrays with different shapes, making code more concise and readable. It is particularly useful in scenarios involving numerical operations, data manipulation, and transformations, contributing to the efficiency and flexibility of array-based computations in various applications.