# **`Data Science Learners Hub`**

**Module : Python**

**email** : [datasciencelearnershub@gmail.com](mailto:datasciencelearnershub@gmail.com)

### **`#1: Introduction to NumPy and Arrays in Python`**

1. **Overview of NumPy:**
   - What is NumPy?
   - Importance in scientific computing and data analysis.

2. **Installation and Importing:**
   - Installing NumPy using pip.
   - Importing NumPy in a Python script or Jupyter notebook.

3. **NumPy Arrays:**
   - Understanding arrays as the core data structure.
   - Creating arrays: `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`.

4. **Array Attributes:**
   - Shape, size, and dimensions of arrays.
   - Data types in NumPy arrays.

5. **Indexing and Slicing:**
   - Accessing elements and subarrays in NumPy arrays.
   - Slicing and its importance.

#### **`1. Overview of NumPy:`**

NumPy, short for Numerical Python, is a powerful open-source library in Python designed for numerical and mathematical operations. It provides support for large, multi-dimensional arrays and matrices, along with an extensive collection of high-level mathematical functions to operate on these arrays. NumPy is a fundamental library in the Python data science ecosystem and is widely used in various scientific and engineering disciplines.

**Significance in Scientific Computing:**

1. **Efficient Array Operations:**
   - NumPy's core feature is its ability to handle arrays efficiently. These arrays are the building blocks for numerical computation in Python.
   - `Example`: In physics simulations, representing vectors and matrices efficiently is crucial. NumPy's arrays make these operations faster and more memory-efficient.

2. **Mathematical Functions:**
   - NumPy provides a vast array of mathematical functions, including trigonometric, logarithmic, statistical, and linear algebra operations.
   - `Example`: In statistical analysis, calculating mean, median, and standard deviation of a dataset can be done succinctly with NumPy functions.

3. **Broadcasting:**
   - NumPy allows operations on arrays of different shapes and sizes, a feature known as broadcasting. This simplifies element-wise operations and makes code more readable.
   - `Example`: In image processing, when you want to add a constant value to each pixel, broadcasting in NumPy streamlines the operation.

4. **Integration with Other Libraries:**
   - NumPy seamlessly integrates with other libraries in the Python ecosystem, such as pandas for data manipulation and Matplotlib for data visualization.
   - `Example`: In a data analysis project, NumPy arrays can be easily passed to pandas DataFrames for advanced data manipulations.

**Real-world Examples:**

1. **Medical Imaging:**
   - NumPy is extensively used in medical imaging for tasks such as processing, analyzing, and visualizing medical images.
   - `Example`: MRI or CT scan data, represented as NumPy arrays, can be manipulated to extract meaningful information about tissues and organs.

2. **Physics Simulations:**
   - In physics, simulations often involve complex mathematical operations on large datasets. NumPy accelerates these simulations.
   - `Example`: Modeling the behavior of particles in a collider, where numerical simulations require efficient array operations for position and velocity calculations.

3. **Financial Modeling:**
   - Financial analysts use NumPy for modeling and analyzing financial data due to its efficient array operations and mathematical functions.
   - `Example`: Portfolio optimization, where arrays represent asset prices and NumPy functions help in calculating returns and risks.

4. **Machine Learning:**
   - NumPy is a foundational library in machine learning. It is used for handling input data, representing parameters in models, and performing mathematical operations.
   - `Example`: In a neural network, weights and biases are often represented as NumPy arrays, and operations involve efficient array manipulations.

NumPy's efficiency, flexibility, and rich functionality make it an indispensable tool in scientific computing, data analysis, and various research domains, contributing significantly to the Python ecosystem's strength in these areas.

#### **`2. Installing and Importing of NumPy:`**

**Installing NumPy using pip:**
To install NumPy using pip, you can use the following command in your terminal or command prompt:

```bash
pip install numpy
```

This command fetches the latest version of NumPy from the Python Package Index (PyPI) and installs it on your system.

**Common Installation Issues and Resolutions:**

1. **Outdated pip:**
   - **Issue:** An outdated pip version might cause installation problems.
   - **Resolution:** Upgrade pip using the command: `pip install --upgrade pip`.

2. **Dependencies:**
   - **Issue:** NumPy relies on certain dependencies, and missing or outdated ones can lead to installation failures.
   - **Resolution:** Ensure that you have the necessary build tools and development libraries installed. On Windows, you might need Microsoft Visual C++ Build Tools. On Linux, you can install them using package managers like `apt` or `yum`.

3. **Virtual Environment:**
   - **Issue:** Installing NumPy in a virtual environment may cause conflicts with system packages.
   - **Resolution:** Activate the virtual environment before running the installation command.

**Importing NumPy:**

Once NumPy is installed, you can import it into your Python script or Jupyter notebook for use in your projects.

**Importing in Python Script:**
```python
# Importing NumPy in a Python script
import numpy as np

# Now, you can use NumPy functions and arrays
arr = np.array([1, 2, 3])
print(arr)
```

**Importing in Jupyter Notebook:**
```python
# Importing NumPy in a Jupyter notebook
import numpy as np

# Now, you can use NumPy functions and arrays
arr = np.array([1, 2, 3])
print(arr)
```

In both cases, `np` is a commonly used alias for NumPy. This alias helps keep the code concise, and it is a widely adopted convention in the Python community.

**Additional Tips:**

- If you encounter issues, check the official [NumPy installation guide](https://numpy.org/install/) for platform-specific instructions and troubleshooting.
- Consider using virtual environments to manage dependencies cleanly.
- For Jupyter notebooks, ensure that the notebook kernel is associated with the correct virtual environment, if any.



#### **`3. NumPy Arrays:`**

**Creating NumPy Arrays:**

NumPy arrays are the foundation of numerical computing in Python. They are homogeneous, multi-dimensional data structures that efficiently store and manipulate numerical data. Here are various methods to create NumPy arrays:

| Method      | Syntax                           | Return Type | Input Parameters                                          | In-Place or Copy | One-liner Explanation                                     | Peculiarities/Considerations                        |
|-------------|----------------------------------|-------------|------------------------------------------------------------|------------------|-----------------------------------------------------------|------------------------------------------------------|
| `array()`   | `np.array(object, ...)`          | `ndarray`   | `object`: Input data, such as a list or tuple               | Copy             | Create an array from an existing Python list or tuple.    |                                                      |
| `zeros()`   | `np.zeros(shape, ...) `          | `ndarray`   | `shape`: Tuple specifying array dimensions                  | In-Place         | Create an array filled with zeros.                         | Default data type is `float64`.                      |
| `ones()`    | `np.ones(shape, ...)  `          | `ndarray`   | `shape`: Tuple specifying array dimensions                  | In-Place         | Create an array filled with ones.                          | Default data type is `float64`.                      |
| `arange()`  | `np.arange([start, ]stop, [step, ])` | `ndarray` | `start`, `stop`, `step`: Parameters defining range         | Copy             | Generate an array with regularly spaced values.           | The `stop` value is exclusive.                      |
| `linspace()`| `np.linspace(start, stop, num=50, ...) `| `ndarray`| `start`, `stop`: Range limits, `num`: Number of points     | Copy             | Generate an array with a specified number of evenly spaced values. | Commonly used for creating time intervals.         |
| `empty()`   | `np.empty(shape, ...) `          | `ndarray`   | `shape`: Tuple specifying array dimensions                  | In-Place         | Create an uninitialized array with shape and dtype.       | Content of the array is not initialized; it may contain garbage values. |
| `full()`    | `np.full(shape, fill_value, ...) ` | `ndarray`  | `shape`: Tuple specifying array dimensions, `fill_value`: Constant value | In-Place | Create an array of specified shape and fill it with a constant value. | Useful for initializing arrays with a specific value. |
| `logspace()`| `np.logspace(start, stop, num=50, ...) `| `ndarray`| `start`, `stop`: Range limits, `num`: Number of points     | Copy             | Generate an array with a specified number of logarithmically spaced values. | Useful for creating logarithmically spaced scales.|


1. **`np.array()`:**
   - The most basic way to create a NumPy array is by converting an existing Python list or tuple.

In [4]:
import numpy as np

arr_from_list = np.array([1, 2, 3, 4, 5])
print(arr_from_list)
print(type(arr_from_list))

[1 2 3 4 5]
<class 'numpy.ndarray'>


**`Note`** : Observe that unlike lists datatypes there are no commas in output incase of NumPy arrays

2. **`np.zeros()`:**
   - Creates an array filled with zeros of a specified shape.

In [5]:
import numpy as np

zeros_array = np.zeros((2, 3))
print(zeros_array)

# Note : (2,3) is tuple
# Why there is '.' after the number '0' ?

[[0. 0. 0.]
 [0. 0. 0.]]


3. **`np.ones()`:**
   - Creates an array filled with ones of a specified shape.

In [6]:
import numpy as np

ones_array = np.ones((3, 2))
print(ones_array)

# Note : (3,2) is tuple
# Why there is '.' after the number '1' ?

[[1. 1.]
 [1. 1.]
 [1. 1.]]


4. **`np.full()`:**
   - Create an array of specified shape and fill it with a constant value

In [1]:
import numpy as np

full_array = np.full((3, 2),6)
print(full_array)

# Note : (3,2) is tuple
# Why there is no '.' after the number '6' ?

[[6 6]
 [6 6]
 [6 6]]


5. **`np.arange()`:**
   - Generates an array with regularly spaced values within a given range.

In [7]:
import numpy as np

range_array = np.arange(0, 10, 2)  # start, stop (exclusive), step
print(range_array)

[0 2 4 6 8]


#### Explanation:

**Is stop inclusive or exclusive in case of arange()?**
In the case of np.arange(), the stop value is exclusive, meaning the generated array stops just before reaching the specified stop value. In the example, the array includes values up to, but not including, 10.

6. **`np.linspace()`:**
   - Generates an array with a specified number of evenly spaced values within a given range.

In [8]:
import numpy as np

linspace_array = np.linspace(0, 1, 5)  # start, stop, number of points
print(linspace_array)

# Does the number 1(stop) get included in the output

[0.   0.25 0.5  0.75 1.  ]


#### Explanation :

- **`np.linspace(0, 1, 5)`:**
   - Generates an array of 5 evenly spaced values between 0 and 1 (inclusive).
   - The `linspace()` function takes three arguments: `start`, `stop`, and `num` (number of points).
   - In this case, it generates an array of 5 points between 0 and 1 (both inclusive).

- **Does the number 1 (stop) get included in the output?**
  - Yes, the number 1 (the `stop` value) is included in the output because the `linspace()` function generates values up to and including the specified `stop` value. In this case, the array includes 1 as one of its values.


7. **`np.logspace()`:**
- Generate an array with a specified number of logarithmically spaced values.

In [2]:
import numpy as np

logspace_array = np.logspace(0, 1, 5)  # start, stop, number of points
print(logspace_array)

[ 1.          1.77827941  3.16227766  5.62341325 10.        ]


#### Explanation:

- `np.logspace(0, 1, 5)`: This function generates an array of values on a logarithmic scale. The parameters are as follows:
  - `0`: Start exponent of the sequence. In this case, it starts at 10^0, which is 1.
  - `1`: Stop exponent of the sequence. It stops at 10^1, which is 10.
  - `5`: Number of points to generate. In this case, it will generate 5 points.


8. **`np.empty()`:**
- Create an uninitialized array with shape and dtype.
- Content of the array is not initialized; **`it may contain garbage values.`**

In [6]:
import numpy as np
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

#### More about empty()
In NumPy, the `empty()` function is used to create an array with a specified shape and data type without initializing the elements to any particular values. The content of the array is not set, and it may contain arbitrary or "garbage" values.

The syntax for the `empty()` function is as follows:

```python
numpy.empty(shape, dtype=float, order='C')
```

- `shape`: Tuple specifying the dimensions of the array.
- `dtype`: Data type of the array. Optional, and the default is `float64`.
- `order`: Specifies whether to store the array data in row-major (`'C'`, default) or column-major (`'F'`) order.

Here's an example of using `empty()`:

```python
import numpy as np

empty_array = np.empty((2, 3))
print(empty_array)
```

In this example, `empty((2, 3))` creates a 2x3 array without initializing the elements. The actual values in the array will depend on the current state of the memory and are not meaningful. It's important to note that if you need an array with initialized values, you should consider using `zeros()`, `ones()`, or another appropriate function depending on your requirements. The `empty()` function is typically used when you need to allocate memory for an array but do not necessarily care about the initial values.

**Real-world Examples:**

1. **Temperature Data:**
   - **Scenario:** You have daily temperature readings for a week.
   - **Application:** Create a NumPy array to store and manipulate temperature data.

In [9]:
temperature_readings = np.array([22.5, 24.0, 23.8, 25.3, 21.7, 22.1, 23.5])
print(temperature_readings)

[22.5 24.  23.8 25.3 21.7 22.1 23.5]


2. **Financial Modeling:**
   - **Scenario:** You are modeling monthly sales figures for a company.
   - **Application:** Use `np.zeros()` to initialize an array for monthly sales and update it as new data becomes available.

In [10]:
monthly_sales = np.zeros(12)
print(monthly_sales)

# Note the output is 1D because no dimensions mentioned in zeros()

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. **Time Series Analysis:**
   - **Scenario:** You need a time series of timestamps at regular intervals.
   - **Application:** Generate a time series using `np.arange()` or `np.linspace()`.

In [11]:
from datetime import datetime, timedelta

start_date = datetime(2022, 1, 1)
time_series = np.array([start_date + timedelta(days=i) for i in range(10)])
print(time_series)


[datetime.datetime(2022, 1, 1, 0, 0) datetime.datetime(2022, 1, 2, 0, 0)
 datetime.datetime(2022, 1, 3, 0, 0) datetime.datetime(2022, 1, 4, 0, 0)
 datetime.datetime(2022, 1, 5, 0, 0) datetime.datetime(2022, 1, 6, 0, 0)
 datetime.datetime(2022, 1, 7, 0, 0) datetime.datetime(2022, 1, 8, 0, 0)
 datetime.datetime(2022, 1, 9, 0, 0) datetime.datetime(2022, 1, 10, 0, 0)]


4. **Physical Simulation:**
   - **Scenario:** Simulating the trajectory of a projectile over time.
   - **Application:** Use `np.linspace()` to generate time intervals and create an array representing the projectile's position at each time step.

In [12]:
time_intervals = np.linspace(0, 5, 100)  # 100 time points from 0 to 5 seconds
print(time_intervals)

[0.         0.05050505 0.1010101  0.15151515 0.2020202  0.25252525
 0.3030303  0.35353535 0.4040404  0.45454545 0.50505051 0.55555556
 0.60606061 0.65656566 0.70707071 0.75757576 0.80808081 0.85858586
 0.90909091 0.95959596 1.01010101 1.06060606 1.11111111 1.16161616
 1.21212121 1.26262626 1.31313131 1.36363636 1.41414141 1.46464646
 1.51515152 1.56565657 1.61616162 1.66666667 1.71717172 1.76767677
 1.81818182 1.86868687 1.91919192 1.96969697 2.02020202 2.07070707
 2.12121212 2.17171717 2.22222222 2.27272727 2.32323232 2.37373737
 2.42424242 2.47474747 2.52525253 2.57575758 2.62626263 2.67676768
 2.72727273 2.77777778 2.82828283 2.87878788 2.92929293 2.97979798
 3.03030303 3.08080808 3.13131313 3.18181818 3.23232323 3.28282828
 3.33333333 3.38383838 3.43434343 3.48484848 3.53535354 3.58585859
 3.63636364 3.68686869 3.73737374 3.78787879 3.83838384 3.88888889
 3.93939394 3.98989899 4.04040404 4.09090909 4.14141414 4.19191919
 4.24242424 4.29292929 4.34343434 4.39393939 4.44444444 4.4949

#### **`4. Array Attributes:`**

**Exploring NumPy Array Attributes:**

NumPy arrays come with several attributes that provide crucial information about their structure and content. Understanding these attributes is essential for effective array manipulation and analysis. Here are some key attributes:

**Note:**
- `shape`, `ndim` (number of dimensions), `size` and `dtype` are attributes of NumPy arrays, not functions or constants. Attributes are properties associated with an object, and in this context, they provide information about the structure and characteristics of a NumPy array.

Here's a brief explanation of each:

1. **Shape (`shape`):**
   - Represents the dimensions of the array, indicating the size along each axis.
   - Example:
     ```python
     import numpy as np

     arr = np.array([[1, 2, 3], [4, 5, 6]])
     print("Array Shape:", arr.shape)  # Output: (2, 3)
     ```

2. **Size (`size`):**
   - Denotes the total number of elements in the array.
   - Example:
     ```python
     import numpy as np

     arr = np.array([[1, 2, 3], [4, 5, 6]])
     print("Array Size:", arr.size)  # Output: 6
     ```

3. **Dimensions (`ndim`):**
   - Indicates the number of axes or dimensions of the array.
   - Example:
     ```python
     import numpy as np

     arr = np.array([[1, 2, 3], [4, 5, 6]])
     print("Number of Dimensions:", arr.ndim)  # Output: 2
     ```

4. **Data Type (`dtype`):**
   - Specifies the type of elements in the array, such as integers, floats, or others.
   - Example:
     ```python
     import numpy as np

     arr = np.array([1, 2, 3], dtype=float)
     print("Array Data Type:", arr.dtype)  # Output: float64
     ```


**Importance of Understanding Attributes:**

1. **Shape and Broadcasting:**
   - **Scenario:** You have two arrays of different shapes, and you want to perform element-wise operations.
   - **Application:** Understanding the shapes of arrays helps in deciding whether broadcasting (element-wise operations on arrays of different shapes) is possible.

In [1]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array
arr2 = np.array([10, 20, 30]) # Note : here arr2 shape is (3,) its 1D array with 3 columns
result = arr1 + arr2  # Broadcasting works due to matching shapes
print(arr1.shape)
print(arr2.shape)

print(result)

(2, 3)
(3,)
[[11 22 33]
 [14 25 36]]


2. **Memory Usage with Size:**
   - **Scenario:** You are working with large datasets and need to manage memory efficiently.
   - **Application:** Knowing the size of an array allows you to estimate its memory requirements and optimize your program accordingly.

In [15]:
import numpy as np

big_array = np.random.random((1000, 1000))
print("Memory Usage (MB):", big_array.nbytes / (1024 * 1024))

Memory Usage (MB): 7.62939453125


3. **Dimensionality and Data Analysis:**
   - **Scenario:** You are analyzing a dataset with multiple variables.
   - **Application:** The number of dimensions (`ndim`) indicates the number of variables, aiding in data exploration and analysis.

In [2]:
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Number of Variables:", data.ndim)  # Output: 2
print(data.shape)

Number of Variables: 2
(3, 3)


4. **Data Type and Precision:**
   - **Scenario:** You are working with financial data and need precise calculations.
   - **Application:** Specifying the data type helps control the precision of calculations, which is crucial in financial and scientific applications.

In [17]:
import numpy as np

financial_data = np.array([100.25, 150.67, 200.32], dtype=np.float32)
print(financial_data)

[100.25 150.67 200.32]


Understanding these attributes enhances your ability to manipulate and analyze data efficiently, leading to more effective use of NumPy in practical scenarios.

#### **`5. Indexing and Slicing in NumPy:`**


**Accessing Elements:**

1. **Indexing:**
   - Individual elements in a NumPy array can be accessed using square brackets and indices.
   - Example:
     ```python
     import numpy as np

     arr = np.array([10, 20, 30, 40, 50])
     element = arr[2]  # Access the element at index 2
     ```

2. **Slicing:**
   - Slicing allows you to extract a portion of an array by specifying a range of indices.
   - Example:
     ```python
     import numpy as np

     arr = np.array([10, 20, 30, 40, 50])
     subarray = arr[1:4]  # Extract elements from index 1 to 3
     ```

**Accessing Subarrays:**

1. **Indexing for 2D Arrays:**
   - For 2D arrays, use indexing with multiple indices or a tuple of indices to access elements.
   - Example:



In [18]:
import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = arr_2d[1, 2]  # Access the element at row 1, column 2
print(element)

# Note : rows and columns start with 0

6



2. **Slicing for 2D Arrays:**
   - Slicing works along each axis, allowing the extraction of subarrays.
   - Example:
 

In [19]:
import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
subarray = arr_2d[0:2, 1:3]  # Extract a subarray from rows 0 to 1 and columns 1 to 2
print(subarray)

[[2 3]
 [5 6]]


**Explanation:**

2. **Creating a 2D NumPy Array:**
   - `arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`: Creates a 2D NumPy array (`arr_2d`) with three rows and three columns.

3. **Extracting a Subarray:**
   - `subarray = arr_2d[0:2, 1:3]`: Uses slicing to extract a subarray from `arr_2d`. 
     - `0:2` specifies the rows from index 0 (inclusive) to 2 (exclusive), which includes rows 0 and 1.
     - `1:3` specifies the columns from index 1 (inclusive) to 3 (exclusive), which includes columns 1 and 2.
   - The resulting subarray is a 2x2 matrix.

4. **Printing the Subarray:**
   - `print(subarray)`: Outputs the extracted subarray.
  
**Explanation:**

The original array `arr_2d` looks like this:
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

The slicing operation `arr_2d[0:2, 1:3]` extracts the subarray consisting of rows 0 and 1, and columns 1 and 2. The resulting `subarray` is:
```
[[2, 3],
 [5, 6]]
```

So, when you run the code and print `subarray`, the output will be:
```
[[2, 3],
 [5, 6]]
```

This demonstrates how NumPy's slicing capabilities allow you to efficiently extract specific portions of a multi-dimensional array, which is particularly useful in various data manipulation and analysis tasks.

**Real-world Examples:**

1. **Time Series Analysis:**
   - **Scenario:** Analyzing a specific time window in a time series dataset.
   - **Application:** Use slicing to extract data for a specific time period, aiding in trend analysis.

In [22]:
import numpy as np

time_series = np.array([10, 15, 20, 25, 30, 35, 40])
specific_period = time_series[2:5]  # Extract data for time steps 2 to 4
print(specific_period)

[20 25 30]


2. **Financial Data Analysis:**
   - **Scenario:** Analyzing stock prices during a specific period.
   - **Application:** Use slicing to extract data for a specific date range, facilitating trend analysis.

In [23]:
import numpy as np

stock_prices = np.array([150.5, 155.2, 160.8, 156.3, 162.0])
specific_period = stock_prices[1:4]  # Extract prices for a specific date range
print(specific_period)

[155.2 160.8 156.3]


**Efficient Analysis of Large Datasets:**

- **Memory Efficiency:**
  - Slicing allows working with a subset of data without loading the entire dataset into memory, making it memory-efficient.
  
- **Parallel Processing:**
  - NumPy's ability to efficiently slice arrays enables parallel processing, essential for analyzing large datasets in parallel.

- **Speed Optimization:**
  - By slicing and accessing only the necessary portions of data, computations become more efficient, leading to faster analysis.

In summary, indexing and slicing in NumPy are powerful tools for extracting specific elements or subarrays, and they play a crucial role in various real-world scenarios, particularly in handling and analyzing large datasets efficiently.

#### **`Understanding Matrices`**

**Matrix Addition** : https://www.youtube.com/watch?v=ZCmVpGv6_1g

**Matrix Multiplication**: 

https://www.youtube.com/watch?v=o6tGHLkZvVM

https://youtu.be/RE-nDY2aWso

Multiplication in Numpy is of two types
- Element wise mul
- dot product mul


In [3]:
import numpy as np

a = np.array([[1,2], [3,4]])
b = np.array ([[3,9], [5,8]])

In [5]:
a*b # by default its doing element wise mul

array([[ 3, 18],
       [15, 32]])

#### Dot Multiplication

In [6]:
np.dot(a,b)

array([[13, 25],
       [29, 59]])

#### Note:
- Matrices A(mxn), B(nxp) then 'n' should be matching in case of Dot products. The resultant matrix will have order of mxn
- Dot product of A.B is not equal to B.A i.e they dont have associative product.
- 

#### **`Understanding Broadcasting`**

**YouTube Videos** :

[https://youtu.be/0u9OzBSRZec](https://youtu.be/0u9OzBSRZec)

[https://youtu.be/oG1t3qlzq14](https://youtu.be/oG1t3qlzq14)

#### **`Broadcasting Rules in NumPy`:**

NumPy's broadcasting rules determine how arrays with different shapes are combined in element-wise operations. Broadcasting allows NumPy to perform operations on arrays of different shapes without the need for explicit looping. The key broadcasting rules are as follows:

1. **Dimensions Compatibility:**
   - Two dimensions are compatible when they are equal or one of them is 1.
   - For example, a 3x5 array can be broadcasted with a 1x5 array, as their dimensions are compatible.

2. **Size Compatibility:**
   - Arrays with smaller dimensions are padded with ones on their left side until their shapes match.
   - For example, a 3x1 array can be broadcasted with a 3x5 array by duplicating its column along the new axis.

3. **Arrays with the Same Number of Dimensions:**
   - If two arrays have the same number of dimensions, their shapes must be compatible along each dimension.
   - For example, a 3x5 array can be broadcasted with another 3x5 array.

4. **Broadcasting Along Multiple Dimensions:**
   - Broadcasting extends to multiple dimensions simultaneously, but it must follow the rules for each dimension.
   - For example, a 3x1x5 array can be broadcasted with a 1x4x1 array.

5. **Size of 1 Dimensions:**
   - Any dimension with size 1 is considered to be effectively stretched or repeated.
   - For example, a 3x1 array can be broadcasted with a 1x5 array.

6. **No Broadcasting:**
   - If the sizes along a particular dimension do not match and none of them is 1, NumPy raises a "ValueError" indicating an incompatible shape for broadcasting.

### Examples:

Here are a few examples illustrating these rules:

```python
import numpy as np

# Example 1: Broadcasting with a scalar
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
scalar_value = 10
result = arr1 + scalar_value

# Example 2: Broadcasting with a 1D array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2

# Example 3: Broadcasting with a 2D array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[10], [20]])
result = arr1 + arr2
```

These examples showcase how NumPy follows the broadcasting rules to perform element-wise operations efficiently across arrays with different shapes. Broadcasting is a powerful feature that simplifies operations and enhances the flexibility of array manipulation in NumPy.


#### Example 1: Broadcasting with a Scalar

```
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
scalar_value = 10
result = arr1 + scalar_value
print("Original Array:")
print(arr1)
print("\nBroadcasting with Scalar:")
print(result)

```

**Output:**

```
Original Array:
[[1 2 3]
 [4 5 6]]

Broadcasting with Scalar:
[[11 12 13]
 [14 15 16]]

```

In this example, the scalar value (10) is broadcasted to each element of the array `arr1`.

**Explanation:**

- **Broadcasting Operation:** The scalar value (10) is broadcasted to each element of the array `arr1`.
- **Broadcasting Rule:** Broadcasting with a scalar involves extending the scalar to match the shape of the array.
- **Result:** Each element of `arr1` is added to the scalar value, resulting in the broadcasted array `result`.

#### Example 2: Broadcasting with a 1D Array

```
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2
print("Original Arrays:")
print(arr1)
print(arr2)
print("\nBroadcasting with 1D Array:")
print(result)

```

**Output:**

```
Original Arrays:
[[1 2 3]
 [4 5 6]]
[10 20 30]

Broadcasting with 1D Array:
[[11 22 33]
 [14 25 36]]

```

In this example, the 1D array `arr2` is broadcasted along its axis to match the shape of `arr1`, and element-wise addition is performed.

**Explanation:**

- **Broadcasting Operation:** The 1D array `arr2` is broadcasted along its axis to match the shape of `arr1`.
- **Broadcasting Rule:** Broadcasting with a 1D array involves extending the smaller dimension (here, the row) to match the larger dimension (row-wise broadcasting).
- **Result:** Element-wise addition is performed between `arr1` and the broadcasted `arr2`, resulting in the broadcasted array `result`.

#### Example 3: Broadcasting with a 2D Array

```
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[10], [20]])
result = arr1 + arr2
print("Original Arrays:")
print(arr1)
print(arr2)
print("\nBroadcasting with 2D Array:")
print(result)

```

**Output:**

```
Original Arrays:
[[1 2 3]
 [4 5 6]]
[[10]
 [20]]

Broadcasting with 2D Array:
[[11 12 13]
 [24 25 26]]

```

In this example, the 2D array `arr2` is broadcasted along its axis to match the shape of `arr1`, and element-wise addition is performed.

**Explanation:**

- **Broadcasting Operation:** The 2D array `arr2` is broadcasted along its axis to match the shape of `arr1`.
- **Broadcasting Rule:** Broadcasting with a 2D array involves extending both dimensions to match the larger shape (both row-wise and column-wise broadcasting).
- **Result:** Element-wise addition is performed between `arr1` and the broadcasted `arr2`, resulting in the broadcasted array `result`.

In summary, broadcasting involves extending smaller dimensions to match larger dimensions, enabling element-wise operations between arrays with different shapes. It allows NumPy to perform operations efficiently and without the need for explicit looping or copying of data. The broadcasting rules ensure that the shapes align correctly for element-wise operations.

These examples demonstrate how broadcasting works in different scenarios, allowing NumPy to handle operations between arrays with different shapes in a convenient and efficient manner.